CREATE DATABASE PROYECTOPOO1;
USE PROYECTOPOO1;
SET LANGUAGE 'us_english';

---CREANDO TABLAS

CREATE TABLE CIUDADANO(
    id_ciudadano INT PRIMARY KEY IDENTITY,
	dui VARCHAR(50),
    nombre VARCHAR(50),
    direccion VARCHAR(50),
    correo VARCHAR(50),
	edad INT,
	telefono VARCHAR(10),
    enfermedad VARCHAR(50) NULL,
    etario BIT,
    institucion VARCHAR(50) NULL,
);

CREATE TABLE CITA(
    id_cita INT PRIMARY KEY IDENTITY,
    estado VARCHAR(50),
    fecha DATETIME,
    lugar VARCHAR(50),
    tipo_vacuna VARCHAR(50),
    dosis VARCHAR(50),
    consentimiento VARCHAR(50),
    id_ciudadano INT,
);

CREATE TABLE CITAXEFECTO(
    id_citaxefecto INT PRIMARY KEY IDENTITY,
    id_cita INT,
    id_efecto INT,
    tiempo TIME
);

CREATE TABLE EFECTO_SECUNDARIO(
    id_efecto INT PRIMARY KEY IDENTITY,
    descripcion VARCHAR(1000),
);

CREATE TABLE CITAXCABINA(
    id_citaxcabina INT PRIMARY KEY IDENTITY,
    id_cita INT,
    id_cabina INT
);

CREATE TABLE CABINA(
    id_cabina INT PRIMARY KEY IDENTITY,
    correo VARCHAR(50),
    direccion VARCHAR(50),
    encargado VARCHAR(50),
	id_empleado INT
);

CREATE TABLE TELEFONOCABINA(
	id_telefonocabina INT PRIMARY KEY IDENTITY,
	telefono VARCHAR(50),
	id_cabina INT
);

CREATE TABLE EMPLEADO(
	id_empleado INT PRIMARY KEY IDENTITY,
	tipo VARCHAR(50),
	nombre VARCHAR(50),
	correo VARCHAR (50),
	direccion VARCHAR (50),
	id_gestor INT
);

CREATE TABLE TELEFONO_EMPLEADO(
	id_telefonoempleado INT PRIMARY KEY IDENTITY,
	telefono VARCHAR(50),
	id_empleado INT
);

CREATE TABLE GESTOR(
	id_gestor INT PRIMARY KEY IDENTITY,
	usuario VARCHAR(50),
	contrasena VARCHAR(50),
	id_rol INT
);

CREATE TABLE ROL(
	id_rol INT PRIMARY KEY,
	descripcion VARCHAR(50)
);

CREATE TABLE HISTORIAL_LOGIN(
	id_historial INT PRIMARY KEY IDENTITY,
	fecha_hora SMALLDATETIME,
	usuario VARCHAR(50),
	descripcion VARCHAR(50),
);

---- CREACION DE LLAVES FORANEAS ----

---CITA
ALTER TABLE CITA
ADD CONSTRAINT FK_CITA_CIUDADANO
FOREIGN KEY (id_ciudadano) REFERENCES CIUDADANO (id_ciudadano);

---CITA EFECTO
ALTER TABLE CITAXEFECTO
ADD CONSTRAINT FK_CITAXEFECTO_CITA
FOREIGN KEY (id_cita) REFERENCES CITA (id_cita)

ALTER TABLE CITAXEFECTO
ADD CONSTRAINT FK_CITAXEFECTO_EFECTO
FOREIGN KEY(id_efecto) REFERENCES EFECTO_SECUNDARIO (id_efecto);

--CITA CABINA
ALTER TABLE CITAXCABINA
ADD CONSTRAINT FK_CITAXCABINA_CITA
FOREIGN KEY(id_cita) REFERENCES CITA (id_cita);

ALTER TABLE CITAXCABINA
ADD CONSTRAINT FK_CITAXCABINA_CABINA
FOREIGN KEY (id_cabina) REFERENCES CABINA (id_cabina);

--CABINA
ALTER TABLE CABINA
ADD CONSTRAINT FK_CABINA_EMPLEADO
FOREIGN KEY (id_empleado) REFERENCES EMPLEADO (id_empleado);

---telefono cabina
ALTER TABLE TELEFONOCABINA
ADD CONSTRAINT FK_TELEFONOCABINA_CABINA
FOREIGN KEY (id_cabina) REFERENCES CABINA (id_cabina);

---EMPLEADO
ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_GESTOR
FOREIGN KEY (id_gestor) REFERENCES GESTOR (id_gestor);

---TELEFONO EMPLEADO
ALTER TABLE TELEFONO_EMPLEADO
ADD CONSTRAINT FK_TELEFONOEMPLEADO_EMPLEADO
FOREIGN KEY (id_empleado) REFERENCES EMPLEADO (id_empleado);

--GESTOR
ALTER TABLE GESTOR
ADD CONSTRAINT FK_GESTOR_ROL
FOREIGN KEY (id_rol) REFERENCES ROL (id_rol);

--INSERTANDO DATOS

INSERT INTO ROL(id_rol, descripcion)
	VALUES(1, 'Create an appointment');
INSERT INTO ROL(id_rol, descripcion)
	VALUES(2, 'Vaccination procces');
INSERT INTO ROL(id_rol, descripcion)
	VALUES(3, 'Administration');
INSERT INTO ROL(id_rol, descripcion)
	VALUES(4, 'Manager');


INSERT INTO GESTOR(usuario, contrasena, id_rol)
	VALUES('Admin', 123456, 4);
